// Generated by scripts/stamp.mjs on npm run build -- do not edit.
// Site Log service worker ef9f353003
const VERSION = "ef9f353003";
const PRECACHE = [
  "./",
  "index.html",
  "tailwind.css?v=7f0a3114",
  "build/bundle.js?v=c16fd98b",
  "build/chunk-XP3IIQST.js",
  "build/chunk-PZPNS2IO.js",
  "build/chunk-YIWAIZ5I.js",
  "build/chunk-6ATBPRIA.js",
  "build/chunk-25DT3VRD.js",
  "build/chunk-TPLT2T2I.js",
  "build/chunk-2OIAAR7D.js",
  "build/chunk-3NXOC7CS.js",
  "build/chunk-4OCQZILE.js",
  "build/chunk-64JS7ZTA.js",
  "build/chunk-6MJ2CZ3I.js",
  "build/chunk-6VNB5OZZ.js",
  "build/chunk-AF2Z24HS.js",
  "build/chunk-ASVWXV3D.js",
  "build/chunk-BCZI6JJE.js",
  "build/chunk-BFQNN4ZP.js",
  "build/chunk-C4MTS4PS.js",
  "build/chunk-CTDIKGXV.js",
  "build/chunk-IGS5IHBC.js",
  "build/chunk-JJZVDK5C.js",
  "build/chunk-KXHLNCJQ.js",
  "build/chunk-O6D3UQM7.js",
  "build/chunk-OQMPU4OA.js",
  "build/chunk-PVMAZ472.js",
  "build/chunk-Q7OBJYOH.js",
  "build/chunk-RJ5O2Z4T.js",
  "build/chunk-TDQ7ALUW.js",
  "build/chunk-TYQ2SBEA.js",
  "build/chunk-TZZM3KHU.js",
  "build/chunk-UXVXJW67.js",
  "build/chunk-VQ6BYHF2.js",
  "build/chunk-Y4YHK4TR.js",
  "build/chunk-ZHAVO34O.js",
  "build/chunk-ZHQIRXZY.js",
  "build/chunk-ZNRE5DWY.js",
  "build/chunk-ZZJJ4RZI.js",
  "manifest.webmanifest",
  "icon.svg",
  "icon-maskable.svg"
];

// What the service worker does with a request, decided from the URL alone so
// it can be tested without a browser. The worker file inlines this module.
//
//   "shell"     the page itself: cached index.html first, refreshed in the
//               background (chunks are content-addressed, so a shell one
//               build old never mixes with new code: it names its own)
//   "immutable" our own static files under the scope, the bundled Firebase
//               SDK chunk included: cache-first
//   "network"   everything else -- Firestore, Auth, the Worker, the weather:
//               untouched, so the app's own offline handling sees the failure

function routeFor({ url, mode, method }, scope) {
  if (method && method !== "GET") return "network";
  let u;
  try {
    u = new URL(url);
  } catch {
    return "network";
  }
  const s = new URL(scope);
  if (u.origin !== s.origin || !u.pathname.startsWith(s.pathname)) return "network";
  const rel = u.pathname.slice(s.pathname.length);
  // Only the app's own page is the shell. Another page under the scope --
  // the privacy notice, say -- is a navigation of its own and must not be
  // answered with the app.
  if (rel === "" || rel === "index.html") return "shell";
  if (mode === "navigate") return "network";
  if (rel.startsWith("build/") || rel === "tailwind.css" || rel === "manifest.webmanifest" || rel.endsWith(".svg"))
    return "immutable";
  return "network";
}

// Never precache anything that talks to a server on our behalf.
function precacheAllowed(url) {
  return !/googleapis\.com|workers\.dev|open-meteo\.com|firestore|identitytoolkit/.test(url);
}

// --- service worker body; scripts/stamp.mjs prepends VERSION, PRECACHE and
// --- the routing function from sw-routes.js and writes the result to sw.js.
/* global VERSION, PRECACHE, routeFor */

const CACHE = "site-log-" + VERSION;
const PREFIX = "site-log-";
const SHELL = "index.html";

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches
      .open(CACHE)
      .then((cache) => cache.addAll(PRECACHE))
      .then(() => self.skipWaiting()),
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((k) => k.startsWith(PREFIX) && k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

// The shell: what is cached, at once; the network's copy replaces it for
// the next open. A shell can only be one build old, and that build's chunks
// are still on the server by their hashed names.
async function shell(request) {
  const cache = await caches.open(CACHE);
  const cached = await cache.match(SHELL);
  const refresh = fetch(request)
    .then((res) => {
      if (res && res.ok) cache.put(SHELL, res.clone());
      return res;
    })
    .catch(() => null);
  if (cached) {
    refresh.catch(() => {});
    return cached;
  }
  const fresh = await refresh;
  return fresh || new Response("Offline", { status: 503, headers: { "Content-Type": "text/plain" } });
}

async function cacheFirst(request) {
  const cache = await caches.open(CACHE);
  const cached = await cache.match(request);
  if (cached) return cached;
  const res = await fetch(request);
  if (res && (res.ok || res.type === "opaque")) cache.put(request, res.clone());
  return res;
}

// The page asks which build serves it; a mismatch with its own shell means
// a newer build is live and a restart is worth offering.
self.addEventListener("message", (event) => {
  if (event.data && event.data.type === "version" && event.ports && event.ports[0]) {
    event.ports[0].postMessage({ version: VERSION });
  }
});

self.addEventListener("fetch", (event) => {
  const route = routeFor(
    { url: event.request.url, mode: event.request.mode, method: event.request.method },
    self.registration.scope,
  );
  if (route === "network") return;
  if (route === "shell") {
    event.respondWith(shell(event.request));
    return;
  }
  event.respondWith(cacheFirst(event.request));
});
