// Stamps content hashes onto the bundle and stylesheet references in
// index.html. Without this, browsers (and the GitHub Pages CDN) happily serve
// a stale bundle after a deploy, so users keep running old code until a hard
// refresh. The chunks the bundle imports carry a hash in their file name
// already, so only the entry and the stylesheet need a stamp.
import { createHash } from "node:crypto";
import { readFileSync, writeFileSync, statSync, readdirSync } from "node:fs";

const hashOf = (path) => createHash("sha256").update(readFileSync(path)).digest("hex").slice(0, 8);

const bundleHash = hashOf("build/bundle.js");
const cssHash = hashOf("tailwind.css");

const htmlPath = "index.html";
const html = readFileSync(htmlPath, "utf8");
let stamped = html.replace(/(<script type="module" src="build\/bundle\.js)(\?v=[a-f0-9]+)?(")/, `$1?v=${bundleHash}$3`);
stamped = stamped.replace(/(<link rel="stylesheet" href="tailwind\.css)(\?v=[a-f0-9]+)?(")/, `$1?v=${cssHash}$3`);

if (!stamped.includes(`build/bundle.js?v=${bundleHash}`)) {
  console.error("stamp: could not find the build/bundle.js script tag in index.html");
  process.exit(1);
}
if (!stamped.includes(`tailwind.css?v=${cssHash}`)) {
  console.error("stamp: could not find the tailwind.css link in index.html");
  process.exit(1);
}

writeFileSync(htmlPath, stamped);

// --- the service worker: a precache list of what the first paint needs, a
// --- version that changes with it, and the routing shared with the tests.
const entry = readFileSync("build/bundle.js", "utf8");
const staticChunks = [...new Set([...entry.matchAll(/(?:from|import)\s*["']\.\/(chunk-[A-Z0-9]+\.js)["']/g)].map((m) => m[1]))];
// The two languages loaded before the first paint are found by content.
// Each language chunk carries its dictionary as JSON text; navToday and
// appLabel together tell English and German from every other file.
const langChunks = readdirSync("build").filter((f) => {
  if (!f.startsWith("chunk-")) return false;
  const text = readFileSync(`build/${f}`, "utf8");
  // Schwiizerduetsch shares the German app name; "Inspektion speichern" is German only.
  // Non-ASCII values are escaped in the chunk (u-escapes), so the markers are plain ASCII.
  return text.includes('inspectSave": "Save inspection"') || text.includes('inspectSave": "Inspektion speichern"');
});
if (langChunks.length !== 2) { console.error(`stamp: expected the English and German chunks, found ${langChunks.length}: ${langChunks.join(", ")}`); process.exit(1); }
const PRECACHE = [
  "./", "index.html", `tailwind.css?v=${cssHash}`, `build/bundle.js?v=${bundleHash}`,
  ...staticChunks.map((c) => `build/${c}`), ...langChunks.map((c) => `build/${c}`),
  "manifest.webmanifest", "icon.svg", "icon-maskable.svg",
];
const routes = readFileSync("sw-routes.js", "utf8").replace(/^export /gm, "");
const body = readFileSync("scripts/sw.template.js", "utf8");
// The version turns with the precache list and with the worker's own code,
// so a change to either installs afresh and retires the old cache.
const VERSION = createHash("sha256").update(PRECACHE.join("|") + bundleHash + cssHash + routes + body).digest("hex").slice(0, 10);
const sw = `// Generated by scripts/stamp.mjs on npm run build -- do not edit.\n// Site Log service worker ${VERSION}\nconst VERSION = ${JSON.stringify(VERSION)};\nconst PRECACHE = ${JSON.stringify(PRECACHE, null, 2)};\n\n${routes}\n${body}`;
writeFileSync("sw.js", sw);
// The shell names its build, so a page can ask the worker which build serves
// it and offer a restart only when the two differ.
const html2 = readFileSync(htmlPath, "utf8");
const meta = `<meta name="site-log-build" content="${VERSION}" />`;
const html3 = /<meta name="site-log-build"[^>]*>/.test(html2) ? html2.replace(/<meta name="site-log-build"[^>]*>/, meta) : html2.replace("</head>", `${meta}
</head>`);
writeFileSync(htmlPath, html3);

const kb = (p) => Math.round(statSync(p).size / 1024);
console.log(`stamp: build/bundle.js?v=${bundleHash} (${kb("build/bundle.js")} KB) · tailwind.css?v=${cssHash} (${kb("tailwind.css")} KB) · sw.js ${VERSION} (${PRECACHE.length} precached)`);
